### ISSUE TITLE
PHP7 beta support

### ISSUE THREAD

**Issue by ferodss** [rlerdorf/php7dev#20]
Would be awesome if we could install PHP7 beta releases

**Comment by rlerdorf** [comment]
If you simply type: makephp 7
you will get the latest.
Or if you specifically want an exact release, checkout the tag and follow the manual build instructions at: https://github.com/rlerdorf/php7dev/#compiling-the-latest-php-7
As in:

```
cd php-src
git pull -r
git checkout tags/php-7.0.0beta1
make distclean
./buildconf -f
./cn
make
sudo make install
newphp 7 debug
```

**Comment by ferodss** [comment]
Awesome! thanks

On Tuesday, July 21, 2015, Rasmus Lerdorf notifications@github.com wrote:

> If you simply type: makephp 7
> you will get the latest.
> Or if you specifically want an exact release, checkout the tag and follow
> the manual build instructions at:
> https://github.com/rlerdorf/php7dev/#compiling-the-latest-php-7
> As in:
> 
> cd php-src
> git pull -r
> git checkout tags/php-7.0.0beta1
> make distclean
> ./buildconf -f
> ./cn
> make
> sudo make install
> newphp 7 debug
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rlerdorf/php7dev/issues/20#issuecomment-123425935.

## 

## Felipe Rodrigues

Software Developer
@ferodss http://twitter.com/ferodss
