### ISSUE TITLE
Apache

### ISSUE THREAD

**Issue by upchuk** [rlerdorf/php7dev#22]
How do you get the PHP working with the installed Apache?

**Comment by ghost** [comment]
I would like to know that too. I want to use Apache instead of Nginx.

**Comment by rlerdorf** [comment]
sudo service nginx stop

Put the following 3 lines in /etc/apache2/conf-available/php.conf:

```
AddHandler php7-script .php
AddType text/html .php
DirectoryIndex index.php
```

sudo a2enconf php
sudo service apache2 start

**Comment by ghost** [comment]
Thanks! :-)

**Comment by ghost** [comment]
If I switch to apache your newphp script doesnt work anymore. How can I fix that I can also switch between PHP versions using apache? Now its always php7

**Comment by rvanlaak** [comment]
:+1: for improvements on easily switching to Apache. Would be awesome

How can we switch our env to Apache with PHP5.6? Does php5.6 require another type of handler? `AddHandler php5-script .php` or `AddHandler php56-script .php` don't seem to work.

**Comment by paulvandermeijs** [comment]
To use PHP 5 replace `/etc/apache2/conf-enabled/php7.conf` and `/etc/apache2/mods-enabled/php7.load` with `/etc/apache2/conf-available/php5.conf` and `/etc/apache2/mods-available/php5.load`.
