### ISSUE TITLE
serve command to add additional sites/apps

### ISSUE THREAD

**Issue by salvo1404** [rlerdorf/php7dev#26]
Hi there, 
not an issue, but It would be nice to have a serve command in the alias like the Laravel Homestead serve command to add additional sites/apps.

**Comment by rlerdorf** [comment]
Pull Request?

**Comment by akyagmur** [comment]
take a look
 @salvo1404
https://github.com/rlerdorf/php7dev/pull/47

**Comment by rlerdorf** [comment]
#47 was merged
