### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by nsanden** [rlerdorf/php7dev#31]
I get this error when I vagrant up
![untitled](https://cloud.githubusercontent.com/assets/2072064/10409207/1c84944a-6ecb-11e5-8cc6-6941ba9751b0.png)

I have the virtual box pack installed

When I try to just run the box in virtualbox, it gets past the menu screen where it asks Debian GNU/Linux OR Advanced options for Debian

However when i choose the first option, it takes me to a black screen and just hangs there forever. Can't type or do anything in that screen.

**Comment by sultanshakir** [comment]
Have you tried upgrading Vagrant and VirtualBox?  I upgraded to Vagrant 1.7.4, VirtualBox and Extension pack 5.0.6 and it worked for me.

**Comment by nsanden** [comment]
Yep i'm running the same versions, 1.7.4 and 5.0.6

**Comment by nsanden** [comment]
Got it working now after i found out VT wasn't enabled in my bios.
