### ISSUE TITLE
Can't access via http://php7dev

### ISSUE THREAD

**Issue by sultanshakir** [rlerdorf/php7dev#32]
I have followed all the installation and setup instructions and I am not able to access the installation via Chrome at http://php7dev.  I added:

`192.168.7.7 php7dev`

to the hosts file on OSX 10.10.5.  I am able to access the ssh via 'vagrant ssh'.

**Comment by nsanden** [comment]
Can you access via http://192.168.7.7 ?

**Comment by rlerdorf** [comment]
192.168.7.7 may not work on your network. 
vagrant ssh in and type: ifconfig
And see if you got another ip via dhcp and use that instead.

**Comment by nsanden** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2072064/10439721/b69c140a-70f0-11e5-9e97-1e83c438f5f8.png)

having same issue. here's ifconfig. i dont see 192 IP. is that bad? :)

**Comment by rlerdorf** [comment]
No, that is fine. Just means that 192.168 ip didn't work on your network. You got 10.0.2.15 instead. So use that.

**Comment by nsanden** [comment]
http://10.0.2.15 isnt working either. Chrome says connection timed out. Am I supposed to start nginx before I try?

**Comment by nsanden** [comment]
BTW thank you Mr. Lerdorf for my very fun career over the last 15 years. :+1:

**Comment by rlerdorf** [comment]
nginx should already be running

It sounds like you have some networking issues between the host machine and virtualbox then. What is your host machine's ip?

**Comment by nsanden** [comment]
192.168.0.7

I did have xampp (apache) and windows firewall running but turned both off just in case.

**Comment by rlerdorf** [comment]
Not sure why 192.168.7.7 didn't work then. When you did the vagrant up command, did it ask you which host interface to bridge to? Which one did you pick if it did?

Try this in the image:

```
sudo ifconfig eth1 192.168.7.7 up
```

Then run /sbin/ifconfig again and see if you have an eth1 with the 192.168.7.7 ip

**Comment by nsanden** [comment]
It did not ask me which host interface to bridge to BUT...

```
sudo ifconfig eth1 192.168.7.7 up
```

Worked! Beautiful PHP INFO page pulled right up! Thanks so much man!

**Comment by rlerdorf** [comment]
So for some reason Vagrant's network configuration step never ran when you brought the machine up. I have no idea why. It seems to work for most people and

```
https://github.com/rlerdorf/php7dev/blob/master/scripts/php7dev.rb#L8
```

looks ok, so I don't see anything to fix here.

**Comment by rlerdorf** [comment]
By the way, what is in your /etc/network/interfaces file? Mine has:

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 192.168.7.7
      netmask 255.255.255.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet dhcp
    post-up route del default dev $IFACE || true
#VAGRANT-END
```

If you have no vagrant entries in there, you can copy that eth1 block to make the 192.168.7.7 interface permanent so you don't need to run that sudo every time you bring it up.

**Comment by nsanden** [comment]
This is all i have. Guess i'll be copying that over thanks.

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
```

**Comment by rlerdorf** [comment]
By the way, I prefer to just let it dhcp which is why I have a dhcp eth2 in there. But it is a bit harder to explain to people that they need to ssh in and check which ip they were assigned and/or check their dhcp server. That way it shows up like any other machine on your local network.

**Comment by sultanshakir** [comment]
Ok I'll run that.

@Nate no I cannot access 192.168.7.7
