### ISSUE TITLE
How can i make apache the default webserver?

### ISSUE THREAD

**Issue by ghost** [rlerdorf/php7dev#35]
Hi,

I know that i can switch from Nginx to Apache after vagrant up using:

sudo service nginx stop
sudo apachectl start

but i have to do this everytime i boot up my vagrant machine. How can i configure apache to be my default webserver and not nginx?

Can you help me please with this?

Thanks!

**Comment by rlerdorf** [comment]
Try:

```
sudo systemctl disable nginx
sudo systemctl enable apache2
```
