### ISSUE TITLE
Node.js and NPM?

### ISSUE THREAD

**Issue by mlocati** [rlerdorf/php7dev#36]
What about installing node.js and grunt by default?
They are quite widely used in build scripts.

I setup my virtual machines with this script:

``` bash
curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g grunt-cli
```

More info about node installed in this way can be found [here](https://github.com/nodesource/distributions#installation-instructions).

**Comment by rlerdorf** [comment]
That seems beyond the scope of a php7dev image. I think most people who use this image won't need it, so I'd like to avoid the extra size. It is easy enough for the people who need it to install it.
