### ISSUE TITLE
How about xdebug

### ISSUE THREAD

**Issue by Kanti** [rlerdorf/php7dev#39]
Is it easily possible to ad xdebug to the current php version?
Maybe it would be nice if there was a command like.
`enablexdebug`
and
`disablexdebug`

or `newphp 7 xdebug`

**Comment by erlendoos** [comment]
I notice that the path to the 'socket' is at /var/run/php-fpm.sock.

How about a setup like this:
/var/run/php53-fpm.sock
/var/run/php54-fpm.sock
/var/run/php55-fpm.sock
/var/run/php56-fpm.sock

I don't know enough about php and how it has implemented fastcgi to find where the current setting can be changed (to serve php as cgi at another .sock)

How can this be done?

**Comment by sambolek** [comment]
Interested in this one as well.

**Comment by wetink-peter** [comment]
+1, this would be very handy!

**Comment by sambolek** [comment]
Short how-to on installing xdebug:
https://github.com/rlerdorf/php7dev/issues/51#issuecomment-189935132

**Comment by rlerdorf** [comment]
xdebug is in the new build
