### ISSUE TITLE
linux-headers-3.2.0-4-amd64 and linux-headers-3.2.0-4-common package files are missing

### ISSUE THREAD

**Issue by deviantintegral** [rlerdorf/php7dev#4]
According to dpkg, these packages are installed, but their files are missing from /usr/src. This breaks dkms and upgrading the Virtualbox guest additions, as they see the packages are installed but then fail on the build process.

This is especially broken if you are using https://github.com/dotless-de/vagrant-vbguest as that will attempt to upgrade the guest additions on the first boot, which first removes the existing additions preventing mounting of /vagrant.

Two solutions I see:
1. Remove the packages entirely, so that vagrant-vbguest will automatically install them if it's in use.
2. Since upgrading guest additions is a common action, shipping with headers isn't a bad idea. In which case, the box should be updated after running `apt-get install --reinstall linux-headers-3.2.0-4-amd64 linux-headers-3.2.0-4-common`.

**Comment by rlerdorf** [comment]
Fixed in version 0.0.5

**Comment by deviantintegral** [comment]
Thanks!
