### ISSUE TITLE
PHP7 memory exhausted when compiling SCSS using compiler from richthegeek

### ISSUE THREAD

**Issue by am05mhz** [rlerdorf/php7dev#40]
Hi, I have a problem with PHP7 memory usage which is the allowed memory limit always exhausted.
I have set the limit to 128MB, which was fine on PHP5.6.
Then I increase the limit to 256MB, memory limit still exhausted.
Even 512MB is not enough.

I have encountered this issue only when using SCSS compiler from [richthegeek](https://github.com/richthegeek/phpsass) which use several classes to do the compiling. Maybe the script has lots of memory leak in which on the previous build got garbage collected rather quickly, or the new PHP7 that is lazily collecting the garbage. Other than compiling SCSS, PHP7 seems to work great.
(note: the SCSS is around 1000 lines of code, and it compiles to around 600 lines of CSS when using PHP5.6)

And btw, I am running this script on PHP7 VC14 x64 Thread Safe build from http://windows.php.net/download as an Apache module on 64bit Apache 2.4 from [Apache Lounge](http://apachelounge.com) on a 64bit Windows 10 machine.

Lastly, I don't know if this is the right place to report bug for windows builds, sorry if I report to the wrong place. Or maybe someone willing to test this out on a linux machine?

**Comment by rlerdorf** [comment]
Definitely the wrong place. Use https://bugs.php.net
