### ISSUE TITLE
Does makephp 7 compile the final release version?

### ISSUE THREAD

**Issue by DeveloperKemal** [rlerdorf/php7dev#42]
Hello,

today I setup your vagrant box and after "vagrant ssh" I run the command "makephp 7". Now "php -v" is showing me version number "7.0.2". 
Is this the final release version of php7?

**Comment by rlerdorf** [comment]
It just builds the latest from the PHP-7.0 branch which is the branch for the final release version, yes.
If you want a specific version you can do this:

cd php-src
git checkout PHP-7.0.0
./vcsclean
./cn70
make
sudo make install

You can edit the cn70 script to change build options. By default it builds the debug version.
