### ISSUE TITLE
vagrant issue

### ISSUE THREAD

**Issue by Morpheus-ro** [rlerdorf/php7dev#49]
Hi,
I want to make something like:
cd /vagrant
mkdir src
ln -s /vagrant/src /var/www/default
 to play around with php7 but I get this error in default-error.log:
 [crit] 511#0: *20 stat() "/var/www/default/src/" failed (13: Permission denied), client: 192.168.7.1, server: localhost, request: "GET /src/ HTTP/1.1", host: "php7.dev"
In the hosts file I have (Ubuntu 14):
192.168.7.7 php7.dev
It's showing phpinfo, but when I try to access "src" it's the phpinfo() displayed + error.

Do you guys have any idea ?

**Comment by ianldgs** [comment]
You can instead edit the nginx conf and change the `root` to `/vagrant/src`

`sudo vim /etc/nginx/conf.d/default.conf`

```
    server_name  localhost;
    root   /vagrant/src; # or any other folder you want
    index  index.php index.html index.htm;
```

**Comment by Morpheus-ro** [comment]
http request -> File not found
Error log-> 2016/01/27 19:15:00 [crit] 1633#0: *7 stat() "/vagrant/src/" failed (13: Permission denied), client: 192.168.7.1, server: localhost, request: "GET / HTTP/1.1", host: "php7.dev"
2016/01/27 19:15:00 [crit] 1633#0: *7 stat() "/vagrant/src/" failed (13: Permission denied), client: 192.168.7.1, server: localhost, request: "GET / HTTP/1.1", host: "php7.dev"
2016/01/27 19:15:00 [error] 1633#0: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.7.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "php7.dev"
