### ISSUE TITLE
Booting more than once fails due to broken /etc/network/interfaces

### ISSUE THREAD

**Issue by deviantintegral** [rlerdorf/php7dev#5]
When I run `vagrant up && vagrant reload` on a fresh clone, the second booting of the box fails. Both times I select to bridge to the ethernet adapter. I'm currently running OS X 10.10.2, Vagrant 1.7.2, and Virtualbox 4.3.20.

Full log: https://gist.github.com/deviantintegral/c08be1445468a915423d

The relevant error:

```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1

Stdout from the command:



Stderr from the command:

/etc/network/interfaces:28: interface eth2 declared allow-auto twice
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces" 
```

**Comment by rhukster** [comment]
I have the same issue with both virtualbox 4.3.20 and 4.3.22.  Works the first time, but as soon as i **halt** and **up** again, i get that error above.

If you destroy-up-suspend-up it works.  It's the destroy-up-halt-up process that is the issue.

**Comment by rlerdorf** [comment]
This appears to be a Vagrant bug in the latest versions. See https://github.com/mitchellh/vagrant/issues/5180
