### ISSUE TITLE
MySQL host access

### ISSUE THREAD

**Issue by montogeek** [rlerdorf/php7dev#52]
Hi!

What is the mysql default user? root/vagrant does not work:
![screen shot 2016-02-09 at 21 19 47](https://cloud.githubusercontent.com/assets/1002461/12937081/f03e255a-cf72-11e5-9404-b16b89deeba1.png)

**Comment by joachimjusth** [comment]
Hi, I had the same issue.

My fix is to update the vagrant user privilege in the database using this command:
`USE mysql;`
`UPDATE user SET Host = "%" WHERE User = "vagrant";`
`FLUSH PRIVILEGES;`

And for connecting through mysql workbench I set the Mysql Port to 3306 and it's working for me.

**Comment by singleman68** [comment]
Hi.
For me, the next connection parameters are working:
![database_conection](https://cloud.githubusercontent.com/assets/6829092/13039920/a0ce98ce-d373-11e5-87e7-84cec0b28e4e.png)

**Comment by rlerdorf** [comment]
vagrant/vagrant works
