### ISSUE TITLE
v0.1.0 - php70 segmentation fault (Laravel 5.1)

### ISSUE THREAD

**Issue by nanohard** [rlerdorf/php7dev#53]
While using Laravel 5.1, php70 caused a segmentation fault (as noted in Apache error log).
My web application just showed a blank page with both nginx and Apache, noting a 500 error.
I did not check other PHP versions.
Perhaps using DotDeb packages would be better? That's what I did to get it working.

**Comment by vinniejames** [comment]
Seeing the same thing trying to run a Statamic app

**Comment by rlerdorf** [comment]
So follow the instructions and build the latest PHP 7 on it.

**Comment by vinniejames** [comment]
I did follow the instructions 'makephp 7' didn't help

**Comment by rlerdorf** [comment]
Then file a proper bug report with a backtrace and a reproducing script snippet. Simply saying you saw a segfault doesn't help.
